[theme]
base="light"
primaryColor="#1F78B4"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F7F9FC"
textColor="#2C3E50"
font="sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

